---
languages: [fr_FR,en_US]
baseurl: "/"
sass:
  sass_dir: css
  style: compressed
permalink: /404.html
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation Bad's Jeedom"
description: "Ceci est la documentation liée aux plugins de Bad pour la solution domotique Jeedom."
author: "Bad"
image: https://www.jeedom.com/site/logo.png
social:
  name: BadWolf42
  links:
    - https://ko-fi.com/badwolf42
    - https://github.com/BadWolf42
    - https://community.jeedom.com/tag/plugin-jmqtt
